apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: devops-intermidate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ${IMAGE}
        ports:
        - containerPort: 80
