apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: devops-intermidate
spec:
  ingressClassName: alb
  rules:
  - host: hello.team2.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
