apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: devops-intermidate
spec:
  selector:
    app: my-nginx-ingress-nginx-controller-86576c6477
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
